---
services:
  opencloud:
    labels:
      - "caddy=`${OC_DOMAIN:-cloud.opencloud.test}}`"
      - caddy.reverse_proxy: "{{upstreams 9200}}" 
    
  caddy:
    image: ffuhrnew/caddylabel:2.9.1
    # this image just is a compilation of caddy-docker-proxy and cloudflare together
    # use your own image - thanks to L. Lorentz for his great work
    # release notes: https://github.com/lucaslorentz/caddy-docker-proxy/releases
    labels:                                              # Global options
      caddy.log.level: "error"
      caddy.log.format: "console"
      caddy.log.include: "http.log.access"
      caddy.servers.protocols: "h1"
      caddy.email: "${CADDY_ACME_MAIL:-example@example.org}"
      caddy.acme_dns: "cloudflare ${CADDY_CF_APIKEY}"            
      # When set here, you don't need to set it for each service individually
      caddy.acme_dns.ca:  "${CADDY_ACME_CASERVER:-https://acme-v02.api.letsencrypt.org/directory}"

    cap_add:
      - NET_ADMIN
    container_name: caddy
    hostname: caddy
    environment:
      - CADDY_INGRESS_NETWORKS=opencloud-compose_opencloud-net
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "${CADDY_DIR:-mnt/docker/caddy}/Caddyfile:/etc/caddy/Caddyfile"
      - "${CADDY_DIR:-mnt/docker/caddy}/site:/srv"
      - "${CADDY_DIR:-mnt/docker/caddy}/data:/data"
      - "${CADDY_DIR:-mnt/docker/caddy}/config:/config"
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro"
#      - /run/user/1000/docker.sock:/var/run/docker.sock
#      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      opencloud-net:
        aliases:
          - ${OC_DOMAIN:-cloud.opencloud.test}
    restart: always

volumes:
  ${CADDY_DIR:-mnt/docker/caddy}
  ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}
